apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "op-proposer.fullname" . }}
  labels:
    {{- include "op-proposer.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "op-proposer.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "op-proposer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- if and .Values.podAnnotations (not (empty .Values.podAnnotations)) }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      {{- if .Values.config.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.config.metrics.port }}"
        prometheus.io/path: "/metrics"
      {{- end }}
      labels:
        {{- include "op-proposer.labels" . | nindent 8 }}
        {{- if and .Values.podLabels (not (empty .Values.podLabels)) }}
          {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- if and .Values.imagePullSecrets (not (empty .Values.imagePullSecrets)) }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "op-proposer.serviceAccountName" . }}
      {{- if not ( empty .Values.podSecurityContext ) }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end}}
      containers:
        - name: {{ .Chart.Name }}
          command:
            - /bin/sh
            - -c
          args:
            - |
              exec op-proposer
          env:
          - name: PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: {{ ternary (include "op-proposer.fullname" .) .Values.secrets.env.PRIVATE_KEY.secretName (not (empty .Values.secrets.env.PRIVATE_KEY.value)) }}
                key: {{ ternary "privateKey" .Values.secrets.env.PRIVATE_KEY.secretKey (not (empty .Values.secrets.env.PRIVATE_KEY.value)) }}
          - name: NETWORK_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: {{ ternary (include "op-proposer.fullname" .) .Values.secrets.env.NETWORK_PRIVATE_KEY.secretName (not (empty .Values.secrets.env.NETWORK_PRIVATE_KEY.value)) }}
                key: {{ ternary "networkPrivateKey" .Values.secrets.env.NETWORK_PRIVATE_KEY.secretKey (not (empty .Values.secrets.env.NETWORK_PRIVATE_KEY.value)) }}
          - name: L1_RPC
            valueFrom:
              secretKeyRef:
                name: {{ ternary (include "op-proposer.fullname" .) .Values.secrets.env.L1_RPC.secretName (not (empty .Values.secrets.env.L1_RPC.value)) }}
                key: {{ ternary "l1Url" .Values.secrets.env.L1_RPC.secretKey (not (empty .Values.secrets.env.L1_RPC.value)) }}
          {{- if .Values.config.metrics.enabled }}
          - name: PROPOSER_METRICS_PORT
            value: {{.Values.config.metrics.port | default 7300}}
          {{- end}}
          {{- $ := required "Missing required env var: config.env.FACTOY_ADDRESS" .Values.config.env.FACTORY_ADDRESS }}
          {{- range $key, $val := .Values.config.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          {{- if not ( empty .Values.securityContext ) }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.config.metrics.enabled}}
          ports:
            - name: metrics
              containerPort: {{ .Values.services.metrics.port | default 7300 }}
              protocol: TCP
          {{- end }}
          {{- if and .Values.livenessProbe (not (empty .Values.livenessProbe)) }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if and .Values.readinessProbe (not (empty .Values.readinessProbe)) }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if and .Values.resources (not (empty .Values.resources)) }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      enableServiceLinks: {{ .Values.enableServiceLinks }}
      {{- if and .Values.nodeSelector (not (empty .Values.nodeSelector)) }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if and .Values.affinity (not (empty .Values.affinity)) }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if and .Values.tolerations (not (empty .Values.tolerations)) }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
