---
auth:
  # -- Enable auth plugin. Remind to change celo_fullnode.ingress.annotations.konghq.com/plugins to reflect the changes
  enabled: true
# -- List of consumers to create in Kong (each consumer is a different client with different credentials)
consumers:
  - odis
  - mento
  - foundation
# -- Redis password. Redis is used for storing rate limit counters
redisPassword: changeme

rate_limit:
  # -- Enable rate limit plugin. Remind to change celo_fullnode.ingress.annotations.konghq.com/plugins to reflect the changes
  enabled: true
  # -- The entity that will be used when aggregating the limits
  limit_by: consumer
  # -- Rate limit configuration for each client
  limits:
    # -- Number of requests per hour allowed for each consumer
    hour: 100000
    # -- Number of requests per minute allowed for each consumer
    # minute: 3000
    # -- Number of requests per second allowed for each consumer
    # second: 100

# -- Check values at [celo-fullnode chart](../celo-fullnode/README.md)
celo_fullnode:
  replicaCount: 2
  gcp: true
  genesis:
    network: rc1
    networkId: 42220
  geth:
    flags: --txpool.nolocals
    gcmode: full
    syncmode: full
    image:
      imagePullPolicy: IfNotPresent
      repository: us.gcr.io/celo-org/geth
      tag: 1.8.8
    public_ip_per_node: []
    node_keys: []
    resources:
      requests:
        cpu: "4"
        memory: 8Gi
    verbosity: 2
    ws_port: 8545
  ingress:
    enabled: false
    tls:
      - hosts:
        - forno.celo-testnet.org
        secretName: forno.celo-testnet.org-tls
    hosts:
      - forno.celo-testnet.org
    ingressClassName: kong
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      konghq.com/plugins: forno-rate-limit, forno-auth
      konghq.com/strip-path: "true"
      kubernetes.io/tls-acme: "true"
  metrics: true
  pprof:
    enabled: true
    path: /debug/metrics/prometheus
    port: 6060
  storage:
    accessModes: ReadWriteOnce
    enable: true
    size: 100Gi
    storageClass: premium-rwo  # SSD CSI
    snapshot:
      enabled: false
      kind: VolumeSnapshot
      name: forno-snapshot
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 5
      metrics:
      - resource:
          name: cpu
          target:
            averageUtilization: 85
            type: Utilization
        type: Resource
      behavior:
        scaleDown:
          policies:
          - periodSeconds: 60
            type: Pods
            value: 2
          - periodSeconds: 60
            type: Percent
            value: 25
          selectPolicy: Max
          stabilizationWindowSeconds: 1800
        scaleUp:
          policies:
          - periodSeconds: 15
            type: Pods
            value: 2
          - periodSeconds: 15
            type: Percent
            value: 25
          selectPolicy: Max
          stabilizationWindowSeconds: 600
