# Default values for op-proposer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Chart name override
nameOverride: ""
# -- Chart full name override
fullnameOverride: ""

# -- Number of deployment replicas
replicaCount: 1

image:
  # -- Image repository
  repository: us-west1-docker.pkg.dev/blockchaintestsglobaltestnet/dev-images/op-succinct/proposer
  # -- Image pullpolicy
  pullPolicy: IfNotPresent
  # -- Image tag
  # Overrides the image tag whose default is the chart appVersion.
  tag: "edge"

# -- Image pull secrets
imagePullSecrets: []

extraArgs: []

config:
  env:
    # this excludes env-vars that could potentially be a secret (see "secrets below")
    L1_BEACON_RPC: https://celo-l1-beacon.celo-networks-dev.org
    L2_RPC: http://op-geth-sequencer-shared-rpc:8545
    L2_NODE_RPC: http://op-node-sequencer-shared-rpc:9545
    EIGENDA_PROXY_ADDRESS: "http://eigenda-proxy-api:4242" 
    GAME_TYPE: 42
    # required, this is the address of the DisputeGameFactoryProxy contract on the L1
    FACTORY_ADDRESS: ""
    ENABLE_GAME_RESOLUTION: true
    MAX_GAMES_TO_CHECK_FOR_CHALLENGE: 100
    MAX_GAMES_TO_CHECK_FOR_RESOLUTION: 100
    MAX_GAMES_TO_CHECK_FOR_BOND_CLAIMING: 100
    PROPOSAL_INTERVAL_IN_BLOCKS: 20
    FETCH_INTERVAL: 30
  metrics:
    enabled: true
    addr: 0.0.0.0
    port: 7300

secrets:
  env:
    PRIVATE_KEY:
      value: ""
      secretName: ""
      secretKey: ""
    NETWORK_PRIVATE_KEY:
      value: ""
      secretName: ""
      secretKey: ""
    L1_RPC:
      value: ""
      secretName: ""
      secretKey: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

services:
  metrics:
    enabled: true
    type: ClusterIP
    port: 7300
    annotations: {}
    publishNotReadyAddresses: true

# -- Custom pod annotations
podAnnotations: {}
  # prometheus.io/path: /metrics
  # prometheus.io/port: "7300"
  # prometheus.io/scrape: "true"

# -- Custom pod labels
podLabels: {}

# -- Custom pod security context
podSecurityContext: {}
  # fsGroup: 2000

# -- Custom container security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- Container resources
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Liveness probe configuration
livenessProbe: {}
  # httpGet:
  #   path: /healthz
  #   port: healthz

# -- Readiness probe configuration
readinessProbe: {}
  # httpGet:
  #   path: /healthz
  #   port: healthz

# -- Kubernetes node selector
nodeSelector: {}

# -- Kubernetes tolerations
tolerations: []

# -- Kubernetes enableServiceLinks
enableServiceLinks: false

# -- Kubernetes pod affinity
affinity: {}

