# Default values for kona-exeuction-verifier.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Chart name override
nameOverride: ""
# -- Chart full name override
fullnameOverride: ""

image:
  # -- Image repository
  repository: us-west1-docker.pkg.dev/devopsre/dev-images/celo-kona
  # -- Image pullpolicy
  pullPolicy: IfNotPresent
  # -- Image tag
  # Overrides the image tag whose default is the chart appVersion.
  tag: "edge"

# -- Image pull secrets
imagePullSecrets: []

extraArgs: []

config:
  app:
    start_block: ""                   # required
    end_block: ""
    l2_url: ""                        # required
    concurrency: "25"
    extra-env: {}
  telemetry:
    enabled: true
    export_interval_ms: 5000
    otlp_endpoint: "http://grafana-alloy.monitoring:4317"
    otlp_protocol: "grpc"             # grpc or http

persistence:
  enabled: true
  pvc:
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: ""           # set to "-" if you want to manually create persistent volume
    annotations: {}

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Automatically mount a ServiceAccount's API credentials?
  automount: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

services:
  headless:
    annotations: {}
    publishNotReadyAddresses: true

# -- Custom pod annotations
podAnnotations: {}
  # prometheus.io/path: /metrics
  # prometheus.io/port: "7300"
  # prometheus.io/scrape: "true"

# -- Custom pod labels
podLabels: {}

# -- Custom pod security context
podSecurityContext: {}
  # fsGroup: 2000

# -- Custom container security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- Container resources
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Liveness probe configuration
livenessProbe: {}
  # httpGet:
  #   path: /healthz
  #   port: healthz

# -- Readiness probe configuration
readinessProbe: {}
  # httpGet:
  #   path: /healthz
  #   port: healthz

# -- Kubernetes node selector
nodeSelector: {}

# -- Kubernetes tolerations
tolerations: []

# -- Kubernetes enableServiceLinks
enableServiceLinks: false

# -- Kubernetes pod affinity
affinity: {}
