{{- if .Values.secrets.p2pKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "op-bootnode.fullname" . }}
  labels:
    {{- include "op-bootnode.labels" . | nindent 4 }}
data:
  p2p.hex: {{ toString .Values.secrets.p2pKey.value | b64enc | quote }}
{{- end }}
