{{- if .Values.blockscout.dbMaintenance.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-db-maintenance
  labels:
    {{- include "celo.blockscout.labels" . | nindent 4 }}
    component: blockscout-db-maintenance
spec:
  schedule: {{ .Values.blockscout.dbMaintenance.schedule }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
          labels:
            {{- include "celo.blockscout.labels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ .Release.Name }}
          initContainers:
          {{- include "celo.blockscout.initContainer.secrets-init" . | nindent 10 }}
          containers:
          {{- $data := dict "Release" .Release "Values" .Values "Database" .Values.blockscout.indexer.db -}}
          {{- include "celo.blockscout.container.db-terminating-sidecar" $data | nindent 10 }}
          - name: db-script-runner
            image: {{ .Values.blockscout.dbMaintenance.image.repository }}:{{ .Values.blockscout.dbMaintenance.image.tag }}
            imagePullPolicy: Always
            command:
            - /tmp/pod/secrets-init
            args:
            - --provider
            - google
            - /bin/sh
            - -c
            - |
              trap "touch /tmp/pod/main-terminated" EXIT
              /db-maintenance/entry.sh
            env:
            - name: PGHOST
              value: "127.0.0.1"
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: "blockscout"
            - name: PGUSER
              value: {{ .Values.blockscout.shared.secrets.dbUser }}
            - name: PGPASSWORD
              value: {{ .Values.blockscout.shared.secrets.dbPassword }}
            volumeMounts:
            - mountPath: /tmp/pod
              name: temporary-dir
          volumes:
            {{- include "celo.blockscout.volume.temporary-dir" . | nindent 12 }}
          restartPolicy: Never
{{- end }}
