---
# -- Number of celo-blockchain statefulset replicas
replicaCount: 1
# -- Override default name format. Use false to use default name format, or a string to override
fullnameOverride: false

# -- Enables aws specific settings
aws: false
# -- Enables azure specific settings
azure: false
# -- Enables gcp specific settings
gcp: false

ingress:
  # -- Enable ingress resource for rpc and ws endpoints
  enabled: false
  # -- Ingress class name
  ingressClassName: nginx
  # -- Ingress annotations
  annotations: {}
    # kubernetes.io/tls-acme: "true"
  # -- Ingress hostnames
  hosts:
    - celo-fullnode.local
  # -- Ingress TLS configuration
  tls: []
  #  - secretName: celo-fullnode-tls
  #    hosts:
  #      - celo-fullnode.local

# -- Labels to add to `nodeSelector` field of the statefulset
nodeSelector: {}
  # pool: spot

# -- Labels to add to the podTemplateSpec from statefulset
extraPodLabels: {}
  # mode: archive

# -- Tolerations rules to add to `tolerations` field of the statefulset
tolerations: []
# - effect: NoSchedule
#   key: pool
#   operator: Equal
#   value: spot

# -- Additional initContainers to add to the statefulset
extraInitContainers: []

storage:
  # -- Enable persistent storage for the celo-blockchain statefulset
  enable: true
  # -- Name of the storage class to use for the celo-blockchain statefulset
  storageClass: default
  # -- accessMode for the volumes
  accessModes: ReadWriteOnce
  # -- celo-blockchain pvc annotations
  annotations: {}
    # resize.topolvm.io/increase: 10%
    # resize.topolvm.io/storage_limit: 500Gi
    # resize.topolvm.io/threshold: 10%
    # resize.topolvm.io/inodes-threshold: 5%
  # -- Size of the persistent volume claim for the celo-blockchain statefulset
  size: 20Gi
  # -- Include a dataSource in the volumeClaimTemplates
  dataSource: {}
    # apiGroup: snapshot.storage.k8s.io
    # kind: VolumeSnapshot
    # name: forno-snapshot

geth:
  # -- Image for the celo-blockchain statefulset
  image:
    repository: us.gcr.io/celo-org/geth
    tag: 1.8.8
    imagePullPolicy: IfNotPresent
  # -- Resources for `geth` container
  resources:
    requests:
      memory: "8Gi"
      cpu: "3"
    limits: {}
  # -- Blockchain sync mode. Valid values are: full, lightest, light and fast
  syncmode: full
  # -- Blockchain garbage collection mode. Valid values are: full and archive
  gcmode: full
  # -- Use GCS backup. Deprecated
  use_gstorage_data: false
  gcp_workload_idantity_email: ""
  # -- Enable blockchain option `--ping-ip-from-packet`
  ping_ip_from_packet: false
  # -- Enable blockchain option `--use-in-memory-discovery-table`
  in_memory_discovery_table: false
  # -- Loggin verbosity. Valid values are: 0-5. 0 is the least verbose
  verbosity: 2
  # -- Array with Private keys used for as nodekey for the celo-blockchain replicas. Replica 0 will use the first ip, replica 1 the second, etc.
  node_keys: []
  # - 582849f34c5503110c01ec2b50f0537ca0ba2390674ad763e554762cdb02f314
  # - f6e3eeddc80be88946536c6d1818b510d4ae18a80a1ff6ef7eeff75ba3a88d4f
  # -- Array with 'public' ip addresses used for `nat=extip:<ip>` option. Replica 0 will use the first ip, replica 1 the second, etc.
  public_ip_per_node: []
  # - 1.2.3.4
  # - 5.6.7.8
  # -- Type of the LoadBalancer for the service attached to each replica. Each replica of the statefulset will have a service of this type.
  # If type is `LoadBalancer`, it will be created with the `public_ip_per_node` as the `loadBalancerIP`
  service_type: LoadBalancer
  # -- Create a differente service for each protocol
  service_protocols:
  - TCP
  - UDP
  # -- Used if nodePort service type is specified. This is only intended to be used in AWS.
  service_node_port_per_full_node: []
  # -- Expose RPC port externally in the individual replica services
  expose_rpc_externally: false
  # -- API's exposed in the RPC/WS interfaces
  rpc_apis: eth,net,rpc,web3
  # -- Gas cap that can be used in eth_call/estimateGas
  rpc_gascap: 10000000
  # -- Use GPC's `cloud.google.com/neg` annotations to configure NEG for the RPC/WS services
  create_network_endpoint_group: false
  # -- Geth's extra flags options (as string)
  flags: --txpool.nolocals
  # -- Custom script (shell) that runs just before geth process is started
  extra_setup: ""
  # -- Celo-blockchain statefulset `updateStrategy`
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
      # maxUnavailable: 25%
      # maxSurge: 25%
  # -- Maximum number of netwook peers. Includes both inbound and outbound connections, and light clients
  maxpeers: 1150
  light:
    # -- Maximum number of light clients to serve, or light servers to attach to
    maxpeers: 1000
    # -- Maximum percentage of time allowed for serving LES requests (multi-threaded processing allows values over 100)
    serve: 70
  # -- WS-RPC server listening port
  ws_port: 8546
  # -- Pod Affinity
  ## see https://www.verygoodsecurity.com/blog/posts/kubernetes-multi-az-deployments-using-pod-anti-affinity
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: component
              operator: In
              values:
              - celo-fullnode
          topologyKey: failure-domain.beta.kubernetes.io/zone
        weight: 100
  # -- HPA configuration for celo-blockchain statefulset. Check official documentation for more info
  autoscaling:
    # -- Enable HPA for celo-blockchain statefulset
    enabled: false
    # -- Minimum number of replicas
    minReplicas: 1
    # -- Maximum number of replicas
    maxReplicas: 5
    # -- Metric reference for HPA
    metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 85
          type: Utilization
      type: Resource
    # -- HPA behavior configuration
    behavior:
      scaleDown:
        policies:
        - periodSeconds: 60
          type: Pods
          value: 2
        - periodSeconds: 60
          type: Percent
          value: 25
        selectPolicy: Max
        stabilizationWindowSeconds: 1800
      scaleUp:
        policies:
        - periodSeconds: 15
          type: Pods
          value: 2
        - periodSeconds: 15
          type: Percent
          value: 25
        selectPolicy: Max
        stabilizationWindowSeconds: 600
  # -- Pprof configuration for celo-blockchain
  pprof:
    enabled: true
    path: /debug/metrics/prometheus
    port: 6060

# -- Enable celo-blockchain metrics and prometheus scraping
metrics: true

# -- Blockchain genesis configuration
genesis:
  # -- Network ID for custom testnet. Not used in case of mainnet, baklava or alfajores
  networkId: 42220
  # -- Network name. Valid values are mainnet, rc1 (both for mainnet), baklava or afajores
  network: rc1
  # -- Use a custom genesis shared as part of a configmap. Used for custom networks with small genesis files
  useGenesisFileBase64: false
  # -- Base64 encoded genesis file if `useGenesisFileBase64` is set to true
  genesisFileBase64: ""

# -- Enable a CronJob that will delete a pod of the statefulset to force flushing the data to disk
deletePodCronJob:
  enabled: false
  # -- Cron expression for the CronJob. As reference for mainnet, the sync speed is around ~2000 blocks/minute,
  # with a blockTime of 5 seconds, 1 day are 17280 blocks (so one day of sync is around 9 minutes)
  schedule: "0 10,22 * * *"
  # -- Statefulset index to delete
  podIndex: 0
  # -- Extra cmd flags to pass to the delete pod command
  extraFlagsPod: ""
  # -- Extra cmd flags to pass to the delete pvc command
  extraFlagsPvc: ""
  # -- Extra PVC index(es) to skip deletion
  extraSkippedPvc: [1, 2, 3]
