---
apiVersion: v2
name: op-succinct-challenger
description: A Helm chart for the op-succinct challenger
type: application
version: 0.1.0
appVersion: "main"
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
sources:
  - https://github.com/celo-org/op-succinct
