# Default values for op-succinct-challenger.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

op-succinct-base:
  app:
    type: challenger
    binaryName: op-challenger

  config:
    endpoints:
      # --URL of the L1 execution client
      l1_execution: ""
      # -- URL of the L2 execution (op-geth) client
      l2_execution: ""
      # -- URL of the EigenDA proxy
      eigenda_proxy: ""
    game:
      # -- Address of the active L1 `DisputeGameFactoryProxy` address
      dispute_game_factory_address: ""
      # -- enable game-resolution
      resolution: true
      # Percentage (0.0-100.0) of valid games to challenge for testing defense mechanisms
      malicious_challenge_percentage: "0.0"
      # -- maximum size of the queue that processes games for different operations
      max_game_limits:
        # -- queue size to challenge games
        challenge: 100
        # -- queue size to resolve games
        resolution: 100
        # -- queue size to reclaim bonds from games
        bond_claiming: 100
    intervals:
      fetch: 30
    remote_signing:
      # -- use a remote signer for signing the challenger l1 transactions instead
      # -- of reading the "PRIVATE_KEY" env-var and signing locally.
      enabled: true
      # -- Address of the challenger, will get used as the 'from' address in `eth_signTransaction` call
      signer_address: ""
      # -- Address of the op-signer-service that is responsible for the L1 batcher privkey, required when signing.remote = true
      # -- Note that this currently only works, when TLS is disabled in the signer-service
      endpoint: ""
    # -- Use a secret to inject env-vars into the executor.
    # -- The `NETWORK_PRIVATE_KEY` has to be present,
    # -- the `PRIVATE_KEY` is only required when `config.remote_signing.enabled` is `false`.
    secret_env:
      # -- Use an existing kubernetes secret by it's secret name
      existing_name: ""
      # -- If any keys are present here,
      # -- creates a new kubernetes secret, that injects arbitrary env-vars
      # -- into the executor.
      overwrites: {}
    metrics:
      enabled: true
      addr: 0.0.0.0
      port: 7300