# Default values for etherscan-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Chart name override
nameOverride: ""
# -- Chart full name override
fullnameOverride: ""

# -- Number of deployment replicas
replicaCount: 1

image:
  # -- Image repository
  repository: us-west1-docker.pkg.dev/devopsre/etherscan-exporter/etherscan-exporter
  # -- Image pullpolicy
  pullPolicy: IfNotPresent
  # -- Image tag
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# -- Image pull secrets
imagePullSecrets: []

env:
  # -- Env. Var API_KEY. Won't be used if apiKeyExistingSecret is defined
  apiToken: "etherscan-api-key"
  # -- Existing secret for Env. Var API_KEY.
  apiTokenExistingSecret: etherscan-api-key
  # -- Chain ID to get blocks from.
  chainID: "1"
  # -- Period for retrieving Socket.dev scores in hours.
  period: "24"
  # -- Log level.
  logLevel: "info"
  # -- The timeout for requests to Socket.dev, in seconds.
  timeout: "15"
  # -- The number of retries for requests to Socket.dev.
  retries: "5"

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use. If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Custom pod annotations
podAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "9101"
  prometheus.io/scrape: "true"

# -- Custom pod security context
podSecurityContext: {}
  # fsGroup: 2000

# -- Custom container security context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- Liveness probe configuration
livenessProbe:
  timeoutSeconds: 30
  httpGet:
    path: /metrics
    port: http

# -- Readiness probe configuration
readinessProbe:
  timeoutSeconds: 5
  httpGet:
    path: /metrics
    port: http

# -- Startup probe configuration
startupProbe:
  timeoutSeconds: 30
  failureThreshold: 30
  periodSeconds: 10
  httpGet:
    path: /metrics
    port: http

# -- Container resources
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Kubernetes node selector
nodeSelector: {}

# -- Kubernetes tolerations
tolerations: []

# -- Kubernetes pod affinity
affinity: {}
