{{- if .Values.podDisruptionBudget.enabled }}
{{- if and (empty .Values.podDisruptionBudget.minAvailable) (empty .Values.podDisruptionBudget.maxUnavailable) }}
{{- fail "podDisruptionBudget requires either minAvailable or maxUnavailable" }}
{{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "op-geth.fullname" . }}
  labels:
    {{- include "op-geth.labels" . | nindent 4 }}
spec:
  {{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "op-geth.selectorLabels" . | nindent 6 }}
{{- end }}
