apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "op-ufm.fullname" . }}
  labels:
    {{- include "op-ufm.labels" . | nindent 4 }}
data:
  config: |
    {{- tpl .Values.config . | nindent 4 }}