apiVersion: v1
kind: Service
metadata:
  name: {{ include "op-ufm.fullname" . }}
  labels:
    {{- include "op-ufm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "op-ufm.signer-port" . }}
      targetPort: signer
      protocol: TCP
      name: signer
    - port: {{ include "op-ufm.health-port" . }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "op-ufm.selectorLabels" . | nindent 4 }}
