apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
data:
  {{- with .Values.config.app}}
  FROM_BLOCK: "{{required "config.app.from_block is required" .from_block}}"
  TO_BLOCK: "{{required "config.app.to_block is required" .to_block}}"
  RANGE: "{{required "config.app.range is required" .range}}"
  BATCH_SIZE: "{{required "config.app.batch_size is required" .batch_size}}"
  CONCURRENCY: "{{required "config.app.concurrency is required" .concurrency}}"
  {{- end}}
