apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.fullname" . }}-config
data:
  {{- with .Values.config.app}}
  KONA_START_BLOCK: "{{required "config.app.from_block is required" .from_block}}"
  {{- with .to_block}}
  KONA_END_BLOCK: "{{.}}"
  {{- end}}
  KONA_L2_ENDPOINT: "ws://{{required "config.app.l2_url is required" .l2_url}}"
  KONA_CONCURRENCY: "{{.concurrency}}"
  {{- end}}
  {{- with .Values.config.telemetry}}
  {{- if .enabled}}
  OTEL_METRIC_EXPORT_INTERVAL: "{{.export_interval_ms}}"
  OTEL_METRIC_EXPORT_TIMEOUT: "30000"
  {{- end}}
  {{- end}}
