{{- if .Values.bootnode.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-bootnode
  labels:
    {{- include "common.standard.labels" .  | nindent 4 }}
    component: bootnode
spec:
  {{- if $.Values.bootnode.ipAddress }}
  type: LoadBalancer
  loadBalancerIP: {{ $.Values.bootnode.ipAddress }}
  {{- else }}
  type: ClusterIP
  clusterIP: {{ default $.Values.bootnode.defaultClusterIP $.Values.bootnode.ipAddress }}
  {{- end }}
  selector:
    app: {{ template "common.name" . }}
    release: {{ .Release.Name }}
    component: bootnode
  ports:
  - name: discovery
    port: 30301
    protocol: UDP
{{- end }}
