{{- if (not .Values.secrets.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.fullname" . }}-geth-account
  labels:
    {{- include "common.standard.labels" .  | nindent 4 }}
type: Opaque
data:
  accountSecret: {{ .Values.secrets.accountSecret | b64enc }}
  mnemonic: {{ .Values.secrets.mnemonic | b64enc }}
  {{- if .Values.secrets.bootnodePrivatekeyKey }}
  privateKey: {{ .Values.secrets.bootnodePrivatekey | b64enc }}
  {{- end }}
{{- end }}
