apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cel2-migration-tool.serviceAccountName" . }}
  labels:
    {{- include "cel2-migration-tool.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
