{{- if or (or (or (or 
  .Values.secrets.jwt.value
  .Values.secrets.sequencerSigningKey.value)
  .Values.secrets.p2pKeys.value)
  .Values.secrets.l1Url.value)
  .Values.secrets.l1BeaconUrl.value
}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "op-node.fullname" . }}
  labels:
    {{- include "op-node.labels" . | nindent 4 }}
data:
{{- $secrets := dict "jwt" .Values.secrets.jwt.value "sequencerSigningKey" .Values.secrets.sequencerSigningKey.value "p2pKeys" .Values.secrets.p2pKeys.value "l1Url" .Values.secrets.l1Url.value "l1BeaconUrl" .Values.secrets.l1BeaconUrl.value }}
{{- range $key, $value := $secrets }}
  {{- with $value }}
  {{ $key }}: {{ toString . | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
