---
{{- if .Values.env.db.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odis-signer.secret" . }}
  labels:
    {{- include "odis-signer.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "odis-signer.secret" . }}: {{ .Values.env.db.password }}
{{- end }}
