apiVersion: v1
kind: Service
metadata:
  name: {{ include "odis-signer.fullname" . }}
  labels:
    {{- include "odis-signer.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "odis-signer.selectorLabels" . | nindent 4 }}
