apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mcp-server.fullname" . }}
  labels:
    {{- include "mcp-server.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - endpoints
      - persistentvolumeclaims
      - persistentvolumes
      - replicationcontrollers
      - namespaces
      - nodes
      - events
      - resourcequotas
      - limitranges
      - bindings
      - podtemplates
      - serviceaccounts
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]