apiVersion: v1
kind: Service
metadata:
  name: {{ include "rogue-sequencer-watcher.fullname" . }}
  labels:
    {{- include "rogue-sequencer-watcher.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9100
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rogue-sequencer-watcher.selectorLabels" . | nindent 4 }}
