---
apiVersion: v2
appVersion: "0.1.0"
name: rogue-sequencer-watcher
description: Detects OP-Stack sequencer equivocation (misconfigured 2nd sequencer or stolen-key / external rogue sequencer)
type: application
home: https://celo.org
icon: https://pbs.twimg.com/profile_images/1613170131491848195/InjXBNx9_400x400.jpg
version: 0.1.0
sources:
  - https://celo.org
  - https://clabs.co
  - https://github.com/celo-org
  - https://github.com/celo-org/rogue-sequencer-watcher
keywords:
  - OP Stack
  - sequencer
  - equivocation
  - security
  - Celo
maintainers:
  - name: cLabs
    email: devops@clabs.co
    url: https://clabs.co
