apiVersion: v1
kind: ConfigMap
metadata:
  name: {{$appname }}-config
data:
  {{- with .Values.config.app}}
  KONA_START_BLOCK: "{{required "config.app.start_block is required" .start_block}}"
  {{if .end_block}}
  KONA_END_BLOCK: "{{.end_block}}"
  {{- end}}
  KONA_L2_ENDPOINT: "ws://{{required "config.app.l2_url is required" .l2_url}}"
  KONA_CONCURRENCY: "{{.concurrency}}"
  {{- end}}

  {{- with .Values.config.telemetry}}
  {{- if .enabled}}
  OTEL_SERVICE_NAME: "{{$appname }}-config"
  OTEL_METRIC_EXPORT_INTERVAL: "{{.export_interval_ms}}"
  OTEL_METRIC_EXPORT_TIMEOUT: "30000"
  {{- end}}
  {{- end}}
