apiVersion: v1
kind: Service
metadata:
  name: {{ include "gme.fullname" . }}-headless
  labels:
    {{- include "gme.labels" . | nindent 4 }}
  {{- with .Values.services.headless.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: {{ .Values.services.headless.publishNotReadyAddresses }}
  selector:
    {{- include "gme.selectorLabels" . | nindent 4 }}
  ports:
    - name: placeholder
      port: 1
      targetPort: 1
