apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "periodic-chain-call.serviceAccountName" . }}
  labels:
    {{- include "periodic-chain-call.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
